name: Java CI with Maven

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-develop:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Run the Maven verify phase
      env:
        ENCRIPTATIONKEY: ${{secrets.ENCRIPTATIONKEY}}
        ENCRIPTATIONMODE: ${{secrets.ENCRIPTATIONMODE}}
        RAILWAYPASSWORD: ${{secrets.RAILWAYPASSWORD}}
        URLCONNECTION: ${{secrets.URLCONNECTION}}
      run: mvn --batch-mode --update-snapshots verify
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build the custom Docker image
      run: docker build -t ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{github.sha}} .

    - name: show docker images
      run: docker images

    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
          
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{github.sha}}
      
    - name: update docker user in k8 
      run: sed -i 's/{docker_user}/${{secrets.DOCKER_USER}}/g' manifests/k8s.yml

    - name: update model name in k8 
      run: sed -i 's/{model_name}/${{secrets.MODEL_NAME}}/g' manifests/k8s.yml

    - name: update _ by - 
      run: sed -i 's/_/-/g' manifests/k8s.yml

    - name: update sha in k8
      run: sed -i 's/{github.sha}/${{github.sha}}/g' manifests/k8s.yml

    - name: ls -la 
      run: cat manifests/k8s.yml
        
    - uses: okteto/context@2.7.0
      with:
        token: ${{secrets.OKTETO_TOKEN }}

    - name: Deploy and Wait
      uses: okteto/actions/deploy@v1
      env:
        KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}
      with:
        namespace: ${{secrets.OKTETO_NAMESPACE }}
        manifest: manifests/k8s.yml
        tag: ${{ secrets.DOCKER_USERNAME }}/${{secrets.MODEL_NAME}}:${{github.sha}}
